---
title: Blog - Benjamin Kobare
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: bkobare@gmail.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
permalink: ":title/"
baseurl: "/benjamin-kobare-blog"
url: ''
author: Benjamin Kobare
author-pic: benjamin-kobare-portrait.png
about-author: Agricultural marketer and a part-time writer living in Kenya.
phone: 
website: 
linkedin: 
github: 
twitter: 
facebook: 
instagram: 
pinterest: 
mailchimp: 
discus_identifier: benjaminkobare
analytics: 
paginate: 6
paginate_path: "/page:num/"
markdown: kramdown
plugins:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
include:
- _pages
exclude:
- node_modules
- gulpfile.js
- package.json
- yarn.lock
- package-lock.json
- assets/css/sass/
